language: python
sudo: required
service:
    docker

before_install:
    - docker build -t sloto .
    - pip install codecov

script:
    - docker run --name sloto-container sloto make coverage
    - docker cp sloto-container:/code/.coverage .
    - docker cp sloto-container:/code/coverage.xml .
    - codecov

